linky_list: linky_linky.o linky_listy_nodes.o
	gcc -o linky_list linky_linky.o linky_listy_nodes.o
linky_linky.o: linky_linky.c linky_listy_nodes.h
	gcc -c linky_linky.c
linky_listy_nodes.o: linky_listy_nodes.c linky_listy_nodes.h
	gcc -c linky_listy_nodes.c

